#!/usr/bin/env python3
import sys


substitutions = {
    "🤔": "status",  # thinking_face
    "🏁": "deploy",  # chequered_flag
    "🛠": "config",  # hammer_and_wrench
    "😷": "debug-logs",  # face_with_medical_mask
    "📋": "tabular",  # clipboard
    "🤮": "yaml",  # face_vomiting
    "😱": "json",  # face_screaming
    "🔥": "remove-unit",  # fire (need to disamb)
    "✨": "something",  # sparkles
    "👊": "force",  # oncoming_fist

}

args = ['juju']


for word in sys.argv[1:]:
    for emoji, meaning in substitutions.items():
        word = word.replace(emoji, meaning)
    args.append(word)

print(" ".join(args))
