#!/usr/bin/env python3
import os
import subprocess
import sys


substitutions = {
    "🤔": "status",  # thinking_face
    "🏁": "deploy",  # chequered_flag
    "🔧": "config",  # wrench
    "😷": "debug-log",  # face_with_medical_mask
    "📋": "tabular",  # clipboard
    "🤮": "yaml",  # face_vomiting
    "😱": "json",  # face_screaming
    "🤯": "remove-unit",  # exploding_head
    "✨": "add-model",  # sparkles
    "🤝": "add-relation",  # handshake
    "🧯": "resolved",  # fire_extinguisher
    "☠️ ": "remove-machine",  # skull_and_crossbones
    "👊": "force",  # oncoming_fist

}

args = ['juju']


for word in sys.argv[1:]:
    for emoji, meaning in substitutions.items():
        word = word.replace(emoji, meaning)
    args.append(word)

real_mode = os.environ.get("EMOJU_REAL", "") != ""

if real_mode:
    subprocess.call(args)
else:
    print(" ".join(args))
