#!/usr/bin/env python3
import sys

substitutions = {
    "🤔": "status",
}

args = ['juju']

for word in sys.argv[1:]:
    for emoji, meaning in substitutions.items():
        word = word.replace(emoji, meaning)
    args.append(word)

print(" ".join(args))

